add_newline = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[?](bold red)"

[container]
format = "[$symbol$name]($style) "
symbol = "ğŸ“¦"
style = "bold green"

[git_status]
conflicted = "ğŸ’¥"
ahead = "ğŸï¸"
behind = "ğŸ¢"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "âœ…"
renamed = "ğŸ“›"
deleted = "ğŸ—‘ï¸"
