[general]
import = [
    # "~/dotfiles/usr/.config/alacritty/themes/themes/everforest_dark.toml"
    # "~/dotfiles/usr/.config/alacritty/themes/themes/dark_pastels.toml"
    "~/dotfiles/usr/.config/alacritty/themes/catppuccin-macchiato.toml"
]
working_directory = "$HOME"
live_config_reload = true

[window]
opacity = 0.89

[font]
normal.family = "0xProto Nerd Font"
bold.family = "0xProto Nerd Font"
italic.family = "0xProto Nerd Font"
bold_italic.family = "0xProto Nerd Font"
size = 10.5

[cursor]
style.shape = "Beam"
style.blinking = "On"

# [terminal]

# [terminal.shell]
# program = "tmux"
# args = ["new-session", "-A", "-s", "main"]

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
